"""
print("Welcome to Sommai Shop")
print("---------------------------")
print("Apple    3   30THB   90")
print("Banana   1   10THB   10")
print("---------------------------")
print("Total 100THB")
print("Thank You : Sommai Shop")
"""
print("Welcome to Sommai Shop")
print("---------------------------")
print("Apple x", 3, 30, "THB - ", 3 * 30, "THB")
print("Banana x", 4, 40, "THB - ", 4 * 40, "THB")
print("Coconut x", 5, 20, "THB - ", 5 * 20, "THB")
print("Egg x", 6, 5, "THB - ", 6 * 5, "THB")
print("Fan x", 7, 10, "THB - ", 7 * 10, "THB")
print("---------------------------")
print("Total", 90 + 160 + 100 + 30 + 70, "THB")
print("Thank You : Sommai Shop")
